export type ModelCapabilityTag =
  | 'fast'
  | 'flagship'
  | 'cost-effective'
  | 'reasoning'
  | 'math'
  | 'data-analysis'
  | 'coding'
  | 'debugging'
  | 'architecture'
  | 'planning'
  | 'review'
  | 'docs'
  | 'writing'
  | 'chinese'
  | 'tool-use'
  | 'agent'
  | 'vision'
  | 'multimodal'
  | 'image-generation'
  | 'image-editing'
  | 'video-generation'
  | 'long-context';

export interface ModelCatalogEntry {
  id: string;
  name: string;
  summary: string;
  strengths: string;
  tags: ModelCapabilityTag[];
  roleFit: string[];
  multimodal: boolean;
  vision: boolean;
  imageGeneration: boolean;
  contextWindow: string;
  notes?: string;
  sourceUrl: string;
}

export interface ModelProviderCatalog {
  id: string;
  name: string;
  description: string;
  models: ModelCatalogEntry[];
}

export const MODEL_CAPABILITY_TAG_LABELS: Record<ModelCapabilityTag, string> = {
  fast: '快速',
  flagship: '旗舰',
  'cost-effective': '性价比',
  reasoning: '推理',
  math: '数学',
  'data-analysis': '数据分析',
  coding: '代码',
  debugging: '调试',
  architecture: '架构',
  planning: '规划',
  review: '审查',
  docs: '文档',
  writing: '写作',
  chinese: '中文优化',
  'tool-use': '工具调用',
  agent: '智能体',
  vision: '图像理解',
  multimodal: '多模态',
  'image-generation': '图像生成',
  'image-editing': '图像编辑',
  'video-generation': '视频生成',
  'long-context': '长上下文',
};

export const MODEL_CATALOG: ModelProviderCatalog[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    description: '通用推理、代码、规划和多模态能力强，适合作为高价值任务的默认上限模型池。',
    models: [
      {
        id: 'gpt-5.5',
        name: 'GPT-5.5',
        summary: 'OpenAI 主力旗舰通用模型，适合复杂推理、规划、代码和跨领域分析。',
        strengths: '复杂任务拆解、架构设计、代码实现、长文档综合和高质量审查。',
        tags: [
          'flagship',
          'reasoning',
          'math',
          'data-analysis',
          'coding',
          'debugging',
          'architecture',
          'planning',
          'review',
          'tool-use',
          'agent',
          'multimodal',
        ],
        roleFit: ['规划分析', '架构方案', '代码工程师', '代码审查'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '400K（Codex）；API 以 OpenAI 模型页为准',
        notes: '适合作为 Auto Router 高优先级通用强模型。',
        sourceUrl: 'https://platform.openai.com/docs/models',
      },
      {
        id: 'gpt-5.5-mini',
        name: 'GPT-5.5 Mini',
        summary: 'OpenAI 高性价比通用模型，适合日常代码、摘要、规划和轻量工具调用。',
        strengths: '快速问答、轻量代码、摘要改写、结构化输出和中等复杂度规划。',
        tags: ['fast', 'cost-effective', 'coding', 'planning', 'docs', 'writing', 'tool-use'],
        roleFit: ['快速助手', '代码工程师', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '400K（参考 GPT-5.5 系列；以 OpenAI 模型页为准）',
        sourceUrl: 'https://platform.openai.com/docs/models',
      },
      {
        id: 'o4-mini',
        name: 'o4-mini',
        summary: 'OpenAI 小型推理模型，适合数学、代码推理和低成本结构化分析。',
        strengths: '数学推理、代码诊断、数据分析和可验证的分步推理。',
        tags: ['reasoning', 'math', 'data-analysis', 'coding', 'debugging', 'cost-effective'],
        roleFit: ['调试诊断', '代码工程师', '规划分析'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '200K（o 系列常见 API 上下文；以 OpenAI 模型页为准）',
        sourceUrl: 'https://platform.openai.com/docs/models',
      },
      {
        id: 'gpt-image-2',
        name: 'GPT Image 2',
        summary: 'OpenAI 图像生成与编辑模型，适合视觉资产和创意图像生产。',
        strengths: '图像生成、图像编辑、视觉素材草案和多轮图像修改。',
        tags: ['image-generation', 'image-editing', 'multimodal'],
        roleFit: ['图像生成', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: true,
        contextWindow: '图像任务参数以 OpenAI 模型页为准',
        sourceUrl: 'https://platform.openai.com/docs/models',
      },
      {
        id: 'gpt-realtime',
        name: 'GPT Realtime',
        summary: 'OpenAI 实时交互模型，适合语音、多轮低延迟助手和交互式工作流。',
        strengths: '实时对话、低延迟助手、语音交互和工具驱动流程。',
        tags: ['fast', 'multimodal', 'tool-use', 'agent'],
        roleFit: ['快速助手', '规划分析'],
        multimodal: true,
        vision: false,
        imageGeneration: false,
        contextWindow: '实时任务参数以 OpenAI 模型页为准',
        sourceUrl: 'https://platform.openai.com/docs/models',
      },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: '长文档理解、审查、规划和严谨写作表现稳定，适合高风险分析类角色。',
    models: [
      {
        id: 'claude-opus-4.8',
        name: 'Claude Opus 4.8',
        summary: 'Claude 系列旗舰模型，偏强推理、代码审查、复杂规划和文档分析。',
        strengths: '代码审查、风险分析、长文档归纳、架构取舍和复杂规划。',
        tags: [
          'flagship',
          'reasoning',
          'coding',
          'debugging',
          'architecture',
          'planning',
          'review',
          'docs',
          'writing',
          'vision',
          'long-context',
        ],
        roleFit: ['代码审查', '架构方案', '规划分析', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '1M（Claude API 默认）；Claude.ai 付费计划 500K',
        sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/models/overview',
      },
      {
        id: 'claude-sonnet-4.7',
        name: 'Claude Sonnet 4.7',
        summary: '高性能均衡模型，适合日常代码、文档和分析任务。',
        strengths: '代码修改、调试分析、文档整理和中高复杂度问答。',
        tags: ['coding', 'debugging', 'review', 'docs', 'writing', 'vision', 'multimodal'],
        roleFit: ['代码工程师', '调试诊断', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '200K 默认；部分 API/计划可到 1M',
        sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/models/overview',
      },
      {
        id: 'claude-haiku-4.7',
        name: 'Claude Haiku 4.7',
        summary: 'Claude 快速档模型，适合低延迟摘要、分类、轻量问答和批处理。',
        strengths: '快速摘要、文档抽取、低成本问答和轻量审查。',
        tags: ['fast', 'cost-effective', 'docs', 'writing', 'vision', 'multimodal'],
        roleFit: ['快速助手', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '200K',
        sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/models/overview',
      },
    ],
  },
  {
    id: 'agnes',
    name: 'Agnes AI',
    description:
      'Agnes AI 提供 OpenAI 兼容的文本、视觉语言、图像和视频生成能力，适合免费/低门槛多模态接入。',
    models: [
      {
        id: 'agnes-2.0-flash',
        name: 'Agnes 2.0 Flash',
        summary: 'Agnes 文本与视觉语言模型，支持聊天、代码、推理、工具调用、流式输出和图像理解。',
        strengths: '代码辅助、Agent 工作流、工具调用、图像理解、摘要和多模态问答。',
        tags: [
          'fast',
          'cost-effective',
          'reasoning',
          'coding',
          'tool-use',
          'agent',
          'vision',
          'multimodal',
          'long-context',
        ],
        roleFit: ['快速助手', '代码工程师', '调试诊断', '规划分析'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '256K 上下文，64K 最大输出参考限制',
        notes: '官方公开资料标注该限制为 2026-06 的参考值，生产使用以控制台和官方文档为准。',
        sourceUrl: 'https://agnes-ai.com/doc/agnes-20-flash',
      },
      {
        id: 'agnes-image-2.1-flash',
        name: 'Agnes Image 2.1 Flash',
        summary: 'Agnes 最新图像生成与编辑模型，支持高密度视觉生成、灵活尺寸和 URL/Base64 输出。',
        strengths: '图像生成、图像编辑、中文/英文提示词视觉创作和素材草案。',
        tags: ['fast', 'cost-effective', 'image-generation', 'image-editing', 'multimodal'],
        roleFit: ['图像生成', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: true,
        contextWindow: '图像任务参数以 Agnes AI 文档为准',
        sourceUrl: 'https://agnes-ai.com/doc/agnes-image-21-flash',
      },
      {
        id: 'agnes-video-v2.0',
        name: 'Agnes Video v2.0',
        summary: 'Agnes 视频生成模型，支持文生视频、图生视频、多图视频和关键帧动画。',
        strengths: '异步视频生成、短视频素材、关键帧动画和创意内容生产。',
        tags: ['video-generation', 'image-generation', 'multimodal'],
        roleFit: ['图像生成', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '视频任务参数以 Agnes AI 文档为准',
        notes: '视频生成使用异步任务 API，创建任务后通过 video_id 查询结果。',
        sourceUrl: 'https://agnes-ai.com/doc/agnes-video-v20',
      },
    ],
  },
  {
    id: 'google',
    name: 'Google Gemini',
    description: '多模态、长上下文和快速响应覆盖面广，适合快速角色和视觉理解任务。',
    models: [
      {
        id: 'gemini-3.5-flash',
        name: 'Gemini 3.5 Flash',
        summary: 'Gemini 快速档模型，适合低延迟问答、摘要、翻译和轻量多模态任务。',
        strengths: '快速响应、摘要翻译、轻量规划、图像理解和批量文本处理。',
        tags: ['fast', 'cost-effective', 'docs', 'writing', 'vision', 'multimodal', 'long-context'],
        roleFit: ['快速助手', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '1M',
        sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
      },
      {
        id: 'gemini-3.5-pro',
        name: 'Gemini 3.5 Pro',
        summary: 'Gemini 高能力通用模型，适合复杂分析、多模态理解和长上下文任务。',
        strengths: '长上下文、多模态分析、架构规划、代码理解和知识综合。',
        tags: [
          'reasoning',
          'data-analysis',
          'architecture',
          'planning',
          'coding',
          'tool-use',
          'vision',
          'multimodal',
          'long-context',
        ],
        roleFit: ['架构方案', '规划分析', '代码工程师'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '1M',
        sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
      },
      {
        id: 'gemini-3.5-flash-lite',
        name: 'Gemini 3.5 Flash Lite',
        summary: 'Gemini 轻量快速模型，适合高吞吐、低成本文本处理和简单多模态理解。',
        strengths: '批量摘要、翻译、分类、简单视觉理解和低成本自动化。',
        tags: ['fast', 'cost-effective', 'docs', 'writing', 'vision', 'multimodal'],
        roleFit: ['快速助手', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '1M',
        sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
      },
      {
        id: 'imagen-4',
        name: 'Imagen 4',
        summary: 'Google 图像生成模型，适合高质量视觉资产、海报和产品图草案。',
        strengths: '图像生成、视觉设计草案、广告素材和风格化输出。',
        tags: ['image-generation', 'multimodal'],
        roleFit: ['图像生成', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: true,
        contextWindow: '图像任务参数以 Google 模型页为准',
        sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: '性价比和代码/推理能力突出，适合成本敏感的代码、调试和快速分析任务。',
    models: [
      {
        id: 'deepseek-v4-pro',
        name: 'DeepSeek V4 Pro',
        summary: 'DeepSeek 高能力推理模型，适合代码、调试、规划和复杂问答。',
        strengths: '代码实现、调试诊断、推理分析和结构化输出。',
        tags: ['reasoning', 'coding', 'debugging', 'planning', 'review', 'cost-effective'],
        roleFit: ['代码工程师', '调试诊断', '规划分析'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '1M',
        sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
      },
      {
        id: 'deepseek-v4-flash',
        name: 'DeepSeek V4 Flash',
        summary: 'DeepSeek 快速档模型，适合低成本问答、摘要和轻量代码任务。',
        strengths: '快速问答、简单代码、摘要改写和轻量分析。',
        tags: ['fast', 'cost-effective', 'coding', 'docs', 'writing'],
        roleFit: ['快速助手', '文档说明'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '1M',
        sourceUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
      },
      {
        id: 'deepseek-reasoner',
        name: 'DeepSeek Reasoner',
        summary: 'DeepSeek 推理模型，适合复杂逻辑、数学、代码推理和多步骤问题。',
        strengths: '复杂推理、数学题、代码分析和结构化诊断。',
        tags: ['reasoning', 'math', 'coding', 'debugging', 'cost-effective'],
        roleFit: ['调试诊断', '代码工程师', '规划分析'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '1M',
        sourceUrl: 'https://api-docs.deepseek.com/',
      },
    ],
  },
  {
    id: 'qwen',
    name: 'Qwen',
    description: '中文、代码、工具调用和多模态生态覆盖广，适合国内部署和中文场景。',
    models: [
      {
        id: 'qwen3.7-max',
        name: 'Qwen3.7 Max',
        summary: 'Qwen Max 档通用强模型，适合中文复杂任务、代码和规划分析。',
        strengths: '中文任务、代码实现、功能规划、架构分析和文档生成。',
        tags: [
          'reasoning',
          'coding',
          'debugging',
          'architecture',
          'planning',
          'docs',
          'writing',
          'chinese',
          'tool-use',
        ],
        roleFit: ['代码工程师', '规划分析', '架构方案', '文档说明'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '1M（Qwen3.7 Max 公开标注；百炼具体模型以控制台为准）',
        sourceUrl: 'https://help.aliyun.com/zh/model-studio/getting-started/models',
      },
      {
        id: 'qwen-image',
        name: 'Qwen Image',
        summary: 'Qwen 图像生成模型，适合中文提示词下的图像创作和视觉资产生成。',
        strengths: '中文图像生成、视觉素材、海报草图和图文创意。',
        tags: ['image-generation', 'image-editing', 'multimodal', 'chinese'],
        roleFit: ['图像生成', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: true,
        contextWindow: '图像任务参数以阿里云百炼模型页为准',
        sourceUrl: 'https://help.aliyun.com/zh/model-studio/getting-started/models',
      },
      {
        id: 'qwen3.7-coder',
        name: 'Qwen3.7 Coder',
        summary: 'Qwen 代码专长模型，适合中文开发场景、仓库理解和工程实现。',
        strengths: '代码实现、仓库分析、中文技术问答、调试和工具调用。',
        tags: ['coding', 'debugging', 'architecture', 'tool-use', 'agent', 'chinese'],
        roleFit: ['代码工程师', '调试诊断', '架构方案'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '1M（Qwen3.7 系列参考值；百炼具体模型以控制台为准）',
        sourceUrl: 'https://help.aliyun.com/zh/model-studio/getting-started/models',
      },
      {
        id: 'qwen3.7-vl',
        name: 'Qwen3.7 VL',
        summary: 'Qwen 视觉语言模型，适合中文图像理解、截图分析和多模态问答。',
        strengths: '图像理解、截图分析、中文视觉问答和多模态资料整理。',
        tags: ['vision', 'multimodal', 'docs', 'data-analysis', 'chinese'],
        roleFit: ['文档说明', '调试诊断', '快速助手'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '1M（Qwen3.7 系列参考值；百炼具体模型以控制台为准）',
        sourceUrl: 'https://help.aliyun.com/zh/model-studio/getting-started/models',
      },
    ],
  },
  {
    id: 'zai',
    name: 'Z.ai / GLM',
    description: '中文推理、代码和综合任务能力强，适合规划、架构和中文文档场景。',
    models: [
      {
        id: 'glm-5.2',
        name: 'GLM-5.2',
        summary: 'GLM 系列高能力通用模型，适合中文复杂分析、代码和规划任务。',
        strengths: '中文推理、规划分析、架构讨论、代码理解和文档写作。',
        tags: [
          'reasoning',
          'math',
          'data-analysis',
          'coding',
          'architecture',
          'planning',
          'docs',
          'writing',
          'chinese',
        ],
        roleFit: ['规划分析', '架构方案', '代码工程师', '文档说明'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '1M',
        sourceUrl: 'https://docs.z.ai/guides/llm/glm-5.2',
      },
      {
        id: 'glm-5.2-flash',
        name: 'GLM-5.2 Flash',
        summary: 'GLM 快速档模型，适合中文低延迟问答、摘要和轻量代码任务。',
        strengths: '中文摘要、快速问答、轻量代码和文档整理。',
        tags: ['fast', 'cost-effective', 'docs', 'writing', 'coding', 'chinese'],
        roleFit: ['快速助手', '文档说明'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '1M',
        sourceUrl: 'https://docs.z.ai/',
      },
    ],
  },
  {
    id: 'xai',
    name: 'xAI',
    description: 'Grok 系列适合实时信息分析、通用推理、代码和产品规划场景。',
    models: [
      {
        id: 'grok-4.5',
        name: 'Grok 4.5',
        summary: 'xAI 旗舰通用模型，适合复杂推理、实时资料分析和工程问答。',
        strengths: '复杂推理、代码分析、产品规划、实时信息综合和技术问答。',
        tags: ['flagship', 'reasoning', 'coding', 'planning', 'data-analysis', 'tool-use'],
        roleFit: ['规划分析', '代码工程师', '架构方案'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '256K（Grok 4 API 公开值；4.5 以 xAI 文档为准）',
        sourceUrl: 'https://docs.x.ai/docs/models',
      },
      {
        id: 'grok-4.5-fast',
        name: 'Grok 4.5 Fast',
        summary: 'Grok 快速档模型，适合低延迟问答、搜索增强分析和轻量任务。',
        strengths: '快速问答、资料归纳、轻量代码和实时信息摘要。',
        tags: ['fast', 'cost-effective', 'docs', 'data-analysis', 'tool-use'],
        roleFit: ['快速助手', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '2M（Grok 4 Fast 公开值；4.5 Fast 以 xAI 文档为准）',
        sourceUrl: 'https://docs.x.ai/docs/models',
      },
    ],
  },
  {
    id: 'meta',
    name: 'Meta Llama',
    description: 'Llama 系列适合开源生态、自托管、通用推理、代码和多语言场景。',
    models: [
      {
        id: 'llama-4.1-behemoth',
        name: 'Llama 4.1 Behemoth',
        summary: 'Meta Llama 高能力开源权重模型，适合自托管旗舰能力和复杂任务。',
        strengths: '自托管、复杂推理、代码理解、架构讨论和多语言任务。',
        tags: ['flagship', 'reasoning', 'coding', 'architecture', 'planning', 'agent'],
        roleFit: ['架构方案', '规划分析', '代码工程师'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '1M（Llama 4 旗舰档参考；以 Meta 模型页为准）',
        sourceUrl: 'https://ai.meta.com/llama/',
      },
      {
        id: 'llama-4.1-scout',
        name: 'Llama 4.1 Scout',
        summary: 'Llama 快速/高性价比模型，适合自托管助手和批量文本处理。',
        strengths: '自托管、快速问答、摘要、轻量代码和批处理。',
        tags: ['fast', 'cost-effective', 'coding', 'docs', 'writing'],
        roleFit: ['快速助手', '文档说明'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '10M',
        sourceUrl: 'https://ai.meta.com/llama/',
      },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Mistral 覆盖欧洲合规、开源/商用部署、代码、OCR 和多语言任务。',
    models: [
      {
        id: 'mistral-large-3.2',
        name: 'Mistral Large 3.2',
        summary: 'Mistral 旗舰通用模型，适合多语言推理、代码、规划和企业场景。',
        strengths: '多语言任务、代码、企业知识分析、规划和工具调用。',
        tags: ['flagship', 'reasoning', 'coding', 'planning', 'tool-use', 'agent'],
        roleFit: ['规划分析', '代码工程师', '架构方案'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '256K',
        sourceUrl: 'https://docs.mistral.ai/getting-started/models/models_overview/',
      },
      {
        id: 'pixtral-large',
        name: 'Pixtral Large',
        summary: 'Mistral 视觉语言模型，适合图像理解、文档截图分析和多模态问答。',
        strengths: '图像理解、OCR 辅助、截图分析和多模态资料整理。',
        tags: ['vision', 'multimodal', 'docs', 'data-analysis'],
        roleFit: ['文档说明', '调试诊断'],
        multimodal: true,
        vision: true,
        imageGeneration: false,
        contextWindow: '128K',
        sourceUrl: 'https://docs.mistral.ai/getting-started/models/models_overview/',
      },
      {
        id: 'codestral',
        name: 'Codestral',
        summary: 'Mistral 代码专长模型，适合补全、重构、代码问答和工程辅助。',
        strengths: '代码补全、重构、工程问答、轻量调试和开发助手。',
        tags: ['coding', 'debugging', 'cost-effective'],
        roleFit: ['代码工程师', '调试诊断'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '128K',
        sourceUrl: 'https://docs.mistral.ai/getting-started/models/models_overview/',
      },
    ],
  },
  {
    id: 'moonshot',
    name: 'Moonshot / Kimi',
    description: 'Kimi 系列适合中文长上下文、文档理解、代码和成本敏感的知识任务。',
    models: [
      {
        id: 'kimi-k3',
        name: 'Kimi K3',
        summary: 'Kimi 高能力中文通用模型，适合长文档、规划、代码和知识综合。',
        strengths: '中文长文档、产品规划、代码分析、资料综合和写作。',
        tags: ['reasoning', 'coding', 'planning', 'docs', 'writing', 'long-context', 'chinese'],
        roleFit: ['规划分析', '文档说明', '代码工程师'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '2M（Kimi 长上下文档位；具体模型以平台为准）',
        sourceUrl: 'https://platform.moonshot.cn/docs',
      },
      {
        id: 'kimi-k3-fast',
        name: 'Kimi K3 Fast',
        summary: 'Kimi 快速档模型，适合中文摘要、轻量问答和低成本文档处理。',
        strengths: '中文摘要、文档抽取、轻量问答和批量文本处理。',
        tags: ['fast', 'cost-effective', 'docs', 'writing', 'chinese'],
        roleFit: ['快速助手', '文档说明'],
        multimodal: false,
        vision: false,
        imageGeneration: false,
        contextWindow: '2M（Kimi 长上下文档位；具体模型以平台为准）',
        sourceUrl: 'https://platform.moonshot.cn/docs',
      },
    ],
  },
];
